# Generated by Django 5.1.2 on 2024-11-15 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dreams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dream',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_dreams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dream',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='dreams.tag'),
        ),
    ]
