# Generated by Django 5.1.2 on 2024-11-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dream',
            name='status',
            field=models.CharField(choices=[('active', 'Активний'), ('completed', 'Завершено')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='dream',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
