"""
Django settings for mriya project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

#mbkm xwjy fpvd qslf


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tpceuud&_gbgm=@+mwk#!+&yc6qx_qo@gmvk_svtgw$(u^_3^i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS =[
    'django.contrib.sites',
    "daphne",
    "dal",
    "dal_select2",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    "django_select2",
    "channels",
    "tinymce",
    "dreams",
    "my_account",

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

INTERNAL_IPS = [
    "127.0.0.1",
]
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',  # Додати локальні адреси
]
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'CLIENT_ID': '352862610021-qv0rq0pe1q9otb7gk0n4fmuhit6lj7l9.apps.googleusercontent.com',
        'SECRET': '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',
    },
    'github': {

        'APP': {
            'client_id': 'Ov23lic1rIjq8UWqun8y',
            'secret': 'a531f639f64de06701c1d3364c92ff0dde01ae39',
            'key': ''
        }
    },
}
SITE_ID = 1

ROOT_URLCONF = 'mriya.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]




ASGI_APPLICATION = 'mriya.asgi.application'
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                ('rediss://default:AatoAAIjcDEzNDE3NGFjNzUwNDQ0N2FhOWU3ZDZlZGVhOTRhMzFlOXAxMA@deep-lamprey-43880.upstash.io:6379')
            ],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "my_account.CustomUser"

AUTHENTICATION_BACKENDS = [
    'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',  # Це стандартний бекенд, якщо ви хочете використовувати стандартну автентифікацію
]
# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TINYMCE_JS_URL = '/static/dreams/tinymce/tinymce.min.js'
TINYMCE_DEFAULT_CONFIG = {
    "height": "320px",
    "width": "960px",
    "menubar": "file edit view insert format tools table help",
    "plugins": "advlist autolink lists link image charmap print preview anchor searchreplace visualblocks code "
    "fullscreen insertdatetime media table paste code help wordcount spellchecker",
    "toolbar": "undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft "
    "aligncenter alignright alignjustify | outdent indent |  numlist bullist checklist | forecolor "
    "backcolor casechange permanentpen formatpainter removeformat | pagebreak | charmap emoticons | "
    "fullscreen  preview save print | insertfile image media pageembed template link anchor codesample | "
    "a11ycheck ltr rtl | showcomments addcomment code",
    "custom_undo_redo_levels": 10,
    "language": "es_ES",
    "images_upload_url": "/upload_image/",
    "automatic_uploads": True,
    "file_picker_types": "image",
    "file_picker_callback": """
    function (callback, value, meta) {
        if (meta.filetype === 'image') {
            var input = document.createElement('input');
            input.setAttribute('type', 'file');
            input.setAttribute('accept', 'image/*');
            input.onchange = function () {
                var file = this.files[0];
                var reader = new FileReader();
                reader.onload = function () {
                    callback(reader.result, {
                        alt: file.name
                    });
                };
                reader.readAsDataURL(file);
            };
            input.click();
        }
    }
""",
}
TINYMCE_SPELLCHECKER = True
TINYMCE_COMPRESSOR = True


ACCOUNT_EMAIL_VALIDATORS = [
    'django.core.validators.EmailValidator',
]

# Налаштування пошти
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Сервер SMTP для Gmail
EMAIL_PORT = 587  # Порт для TLS
EMAIL_USE_TLS = True  # Використовуємо TLS для безпечного з'єднання
EMAIL_HOST_USER = 'authentication.mriya@gmail.com'  # Ваш Gmail акаунт
EMAIL_HOST_PASSWORD = 'mbkm xwjy fpvd qslf'  # Ваш пароль або App Password
DEFAULT_FROM_EMAIL = 'authentication.mriya@gmail.com'  # Адреса, з якої надсилаються листи


LOGIN_REDIRECT_URL = 'dream_list'
LOGOUT_REDIRECT_URL = 'account_login'

ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # Підтвердження електронної пошти обов'язкове
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3  # Посилання на підтвердження дійсне 3 дні
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True  # Логінити користувача після підтвердження email

ACCOUNT_PASSWORD_RESET_TIMEOUT = 14400  # Час дії посилання для відновлення пароля (4 години)
ACCOUNT_EMAIL_REQUIRED = True  # Вимога наявності email
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'

ACCOUNT_EMAIL_CONFIRMATION_TEMPLATE = 'account/verification_sent.html'
ACCOUNT_EMAIL_CONFIRMATION_REDIRECT_URL = 'email_confirm'






